### ISSUE TITLE
Be consistent between zone and zone_id

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#11]
[`node`](https://github.com/zephyr-data-specs/GMNS/wiki/Node) table uses `zone`

[`location`](https://github.com/zephyr-data-specs/GMNS/wiki/Location) uses `zone_id`

Be consistent about definition and naming.

**Comment by ssmith55** [comment]
Recommend using zone_id, and adding a simple zone table.

**Comment by ianberg-volpe** [comment]
In spec-as-code branch, simple [zone](https://github.com/zephyr-data-specs/GMNS/blob/spec-as-code/Specification/Zone.md) table added, and `node`'s zone field renamed to `zone_id`
