### ISSUE TITLE
Specify default units

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#13]
Several places there are not units specified.  Default units should be specified:

i.e. `width` in [Lanes](https://github.com/zephyr-data-specs/GMNS/wiki/Lane) should probably be specified as feet

**Comment by ssmith55** [comment]
As discussed during today's call with the Zephyr PMC:
Length:  Miles (along a link) or feet (across a link, as in lane width)
Speed:  mi / hour

**Comment by e-lo** [comment]
? for Linear References... feet?

**Comment by e-lo** [comment]
Need to have an optional config file where we specify things like unit overrides.

Suggest a YAML/TOML file with the general format:

```
units:
 - distance_long: miles
 - distance_short: feet
```
