### ISSUE TITLE
Time of day variation is complex for simple changes

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#14]
I'd like to flag what I think is a significant drawback of the current data mode for time of day variable. Specifically, I have found it frustrating that:

1. a simple change by time of day requires many entries, and
2. the same table could use a variety of foreign keys which depend on the entry; this makes merge and joins. 

**I propose that we have the following model to make simple things simple:**

`link` _can be overridden by_ `link_tod` _which can be augmented by_ `link_lanes_tod` 

 - `link` is treated like the default for the whole day; `link_tod` has the same attributes as `link` with the addition of a time of day.   This allows simple changes in lanes, tolls or restrictions by time of day to only have one additional table.  
- `link_lanes_tod` specifies changes to certain lanes by time of day with the assumption that the rest remain as they were. This allows a lane restriction to occur on a single lane without having to specify it for the rest of the lanes (assuming there are no restrictions).

Anything in a link can be overridden by a segment file.

`link` _can be overridden by_ `segment`
`link_tod` can be overridden by `segment_tod`
`link_lanes_tod` can be overridden by_ `segment_lanes_tod` 

Only meso/micro models will need to specify segments (likely) so you wont make simple merges between macro-scale data more complicated by having to do conditional joins depending on segments vs links.

**Comment by ianberg-volpe** [comment]
We have added [TOD.md](https://github.com/zephyr-data-specs/GMNS/blob/spec-as-code/Specification/TOD.md) to the spec-as-code branch, which includes `link_tod, link_lane_tod, segment_tod, segment_lane_tod` files. We also created a new [segment_lane](https://github.com/zephyr-data-specs/GMNS/blob/spec-as-code/Specification/Segment_lane.md) table to mirror `segment_lane_tod` (for lane add/drops, or changes to characteristics of a lane on a segment).

See the entity-relationship diagram below: 
![New link E-R diagram](https://github.com/zephyr-data-specs/GMNS/raw/spec-as-code/Images/ER_diagrams/new_link_er.png)
