### ISSUE TITLE
Allow ad-hoc additional fields rather then explicitly setting a field name as "additional_fields"

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#15]
1. it is confusing what it **is**.
2. what if you have multiple?

**Comment by ssmith55** [comment]
Agreed.  What we had was a placeholder, with the intent of allowing ad-hoc additional fields.

**Comment by joshchea** [comment]
User defined or custom fields could have any name except the required/predefined GMNS field names for the network object in question. This could be enforced by issuing a warning/error when parsing the data in the validation tool by checking set membership against predefined attribute names.
