### ISSUE TITLE
Link TOD

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#19]
Currently the only link attributes that can vary by TOD are allowed_uses and toll: suggest allowing parking, free_speed and capacity to vary by TOD as well. 
Also I'm wondering it would not be more consistent with the overall data structure strategy to associate one TOD "card" or "record" (not sure what we're calling these...) with a single attribute that can be specified as a variable, rather than having the card/record format explicitly include all of the attributes that are allowed to change by TOD.

**Comment by ianberg-volpe** [comment]
I believe this was resolved by the recent pull request, as [`Link_TOD`](https://github.com/zephyr-data-specs/GMNS/blob/master/Specification/TOD.md#Link_TOD) now includes TOD variation for capacity, free_speed, lanes, bike_facility, ped_facility, parking, allowed_uses
