### ISSUE TITLE
field name abbrvs; why not full words?

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#2]
Question:
- I couldn't find an issue or discussion item where it was decided to change the field names to be abbreviations? What is the thinking behind this?

There are some plusses and minuses:

For Abbrvs:
+ can potentially fit things into DBFs, cube, and other places with limits on spaces
+ fewer characters to write

Against Abbvs:
-  hard to remember which way abrr things (or is that Abbv?) 
-  less legible
-  creates inconsistencies across other formats (i.e. osm, shared streets, etc)

**Comment by ssmith55** [comment]
The request was that field names be limited to 10 characters, for improved compatibility with formats that have limits on field names.  We did the following:
-   added a few abbreviations that we hope are obvious
-   made sure that, within a table, first 10 characters of a field name are unique
However, we are not limiting field names to 10 characters

**Comment by ianberg-volpe** [comment]
Commits that make these changes in the example files and conversion tools:
83ccc560a264bddc56d392a50ac5cc44ab37b51d ec0fd320f235dc0efe4fe1db7e823577f1151bf5 9bad897ce7125c0ed08c4cd0fc0a623adb724740 b83dc7f720ba910b847fb3ee9e54b913fd906571
