### ISSUE TITLE
Movement ib_lane

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#20]
definition of "ib_lane" is "Uses lane number"; whereas "ob_lane" is "Uses lane numbers or ranges of numbers"
ib_lane should have the same definition as ob_lane, i.e. support a range of lanes
Also: should indicate the accepted formats for specifying a range of lanes, e.g. "1-3" vs. "1,2,3", etc...

**Comment by ssmith55** [comment]
Good catch.  Thanks.  Any strong preference?  A single lane number may ease programming, at the cost of a few more records (one for each lane).  A range of lane numbers (e.g., 1-3) is more compact, but may make the network generation and validation code more complicated.

**Comment by mike-mahut** [comment]
Sorry just saw this now... its a different email from the one I usually use
(and pay attention to).
One question would be to start with what the validation rule actually is --
for example, is it required that the set of lanes be contiguous?
I would suggest that yes, and most modelling software probably requires
this as well.
In that case, validation would be easier if the spec only allows for 2
numbers, e.g. "1-3", or "1,3", it doesn't really matter that much what the
delimiter is.
Thanks!

**Comment by ianberg-volpe** [comment]
If true that lanes are always contiguous, validation would likely be easier if the start lane and end lane are separate fields, i.e., a movement has `start_ib_lane`, `end_ib_lane`, `start_ob_lane`, `end_ob_lane` fields.
