### ISSUE TITLE
Movement TOD

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#21]
Currently only "allowed_uses" can vary by TOD: suggest allowing capacity to vary by TOD as well.
In addition, "ib_lane" and "ob_lane" can vary by TOD in some situations: in some cases this may be "derived" information, e.g. lane usage changes in time, but I'm not sure if it can be assumed that all cases would fall under this category.

**Comment by mike-mahut** [comment]
In addition, "ib_lane" and "ob_lane" can vary by TOD in some situations.

**Comment by ianberg-volpe** [comment]
Yes, the Movement TOD file should match the other recently edited TOD files

**Comment by ianberg-volpe** [comment]
resolved by #40
