### ISSUE TITLE
Movement ctrl_type and priority

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#22]
The specification for now has no information about movement priority, other than the use of Movement "ctrl_type" to indicate stop and yield.
So, this assumes that any other information about priority, e.g. a left-turn at a signalized intersection that must yield to the opposing traffic, is implicit: i.e. its the same in all networks that this specification is intended to serve. That might be a bit limiting, but perhaps ok for now.
For micro-sim applications there are "gap acceptance" parameters which may vary from location to location and in some cases are adjusted as part of the model calibration. These may be structured in different ways in terms of how defaults are defined (e.g. "left from major street" vs. "left from minor street" for two-way stops).
At the most dis-aggregate level this requires attributes specified for individual pairs of conflicting movements; though it may be sufficient to stick with general categories (like the examples above) which can be modified / over-ridden at individual nodes or movements. Needs discussion.
These categories would have default values which motivates a larger number of categories for "ctrl_type", e.g. so that for different yield cases: e.g. arterial turn channel vs. freeway merge vs. roundabout can have different defaults.

**Comment by ssmith55** [comment]
Control types are currently envisioned as:  No Control, Stop, Yield, Signal.  For non-signalized intersections, it might make sense to add 4-way stop as an option, since its capacity implications are different than those for a 2-way stop.   The added details needed for signalized intersections can be considered in the signal tables:  protected, permissive, RTOR, no movement allowed.

**Comment by mike-mahut** [comment]
The tags look reasonable and provide general descriptive information, though “stop 2-way” and “stop 4-2ay) would be more like node-level tags rather than movement-level tags. 
At a deeper level, inside a traffic model (e.g. meso or micro, though not in static models) there are numeric values associated with the movement which determine the exact behaviour, e.g.  an associated ideal capacity (for different cases as in the tags above) as well as parameters that determine the yielding behaviour (in micro-sim these are called gap acceptance parameters).
For capacities, what I’m referring to is a need for more than 1 capacity value associated with the turning movement (e.g. protected vs. permissive in a signalized case: we need both). I believe that 2 slots are generally enough, i.e. one extra capacity in addition to what is already in the current spec.
Besides capacity we need information related to priority which is sometimes called the “rank”. This tells us, for example, that at a TWSC intersection, the main street (no-stop) movement has the highest priority, left-turn from main street has the next level, through movement from minor (stop) is the next, and then left-turn from minor is the lowest. This could be stored in a single attribute called rank, for example (integer, sort of like facility type).
At a minimum I would recommend having the additional capacity and rank as explicitly supported attributes. 
The last piece of information is what are called gap-acceptance parameters in micro-sim, though other parameters that represent this behaviour may be used in meso-style (flow based) models, which use a different paradigm. For these, I’m wondering if we could just have some generic movement attributes (akin to user-defined attributes) that store this info, remaining agnostic to the traffic model in question. Generally takes 2 of these per movement. (In more customizable micro-sim models, these can be defined for each pair of conflicting movements at the node, but I do not recommend we try to support that necessarily in GNMS).
So, once we have the 2nd capacity value, rank, and gap acceptance parameters, we kind of have everything covered: we don’t really care any more if it’s a yield, freeway merge, roundabout, twsc, awsc, etc… it is all parameterized in the numbers. But these more general descriptive tags are still useful, as they are common terms and in some cases, this may be all that is known. 
Agreed that protected vs. permissive needs to be at the phase level, and that RTOR is sufficient as a “static” attribute, indicating that the movement will have this status in any phase where it has a red signal.

**Comment by ianberg-volpe** [comment]
closed in #40
