### ISSUE TITLE
Signal phase

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#23]
A single signal phase is currently defined as a list of individual cards/records, one for each turning movement. For simplicity -- and ease of eventual validation -- it would be more practical to have a variable-length list indicating all the turning movements associated (having green) with a single phase.

**Comment by ssmith55** [comment]
You might need separate records to distinguish between protected and permissive movements.  

Here is an example.   Three movements:  Left, Thru, Right  (right turn conflicts with a concurrent walk signal, hence is permissive)
Phases are (1) Protected Left and (6) Thru plus permissive left.  You could have two variable length lists with each phase, one for the protected and the other for the permissive movements.  

|  Phase  |  Protected | Permissive  |
| 1        |  L               |                    |
| 6        |  T               |  L R             |

**Comment by mike-mahut** [comment]
Good point about needing to define these tags by phase.

**Comment by ianberg-volpe** [comment]
clsoed in #40
