### ISSUE TITLE
Movement right-turn-on-red

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#24]
This could be handled as a distinct entry within the signal phase, e.g. a separate list of right-turn-on-red movements (or separate state to distinguish from those that have green); or, more commonly, it is a single tag associated with the movement, and the actual phases in which the movement has this state is determined via logical rules embedded in the modeling software.

**Comment by ssmith55** [comment]
The options seem to be:
1.  Consider as part of signal phasing
2.  Or as a control_type within movements:  signal, or signal_with_turn_on_red

**Comment by mike-mahut** [comment]
I think it should be fine as a movement attribute, e.g. as “signal_with_RTOR” as proposed previously in #22 
This would mean that the movement has TOR status in any phase where it has a red signal. That should do it. Contrary to what I wrote in my original comment, there is no need for rules or heuristics when tagging at the movement level (I was thinking of the case where a node is tagged as permitting RTOR, in which case rules are required to figure out which movements that applies to).

**Comment by ianberg-volpe** [comment]
closed in #40
