### ISSUE TITLE
Signal phase concurrency (ring diagram): variability

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#26]
Modern controllers support more than one configuration whereas the current GNMS specification assumes that there is only one arrangement possible at any given node. 
So basically this data structure needs a name or some other identifier other than the node ID itself (which can then be used to refer to it in a "signal timing plan").

**Comment by ssmith55** [comment]
In the "updates" branch, the use of controller_id is proposed, so that one controller can be associated with multiple nodes.

**Comment by mike-mahut** [comment]
Having multiple nodes sharing a single controller ID is useful. It would be good to include as an attribute to at least store this basic association, even without storing other information that would be pertinent to a multi-node controller.
However, my original comment was not about putting multiple nodes under a single controller. It was about being able to define multiple “signal phase concurrency” structures – what are normally referred to as signal plans – for a single node. For example, there would be typically 4 plans at an intersection (am peak, inter-peak, pm peak, off peak). Unless I’m missing something, that is what the signal phase concurrency structure represents.

**Comment by ssmith55** [comment]
timing_plans that apply at different times of day are handled via signal_timing_plan and signal_timing_phase.  The four-plan example would be handled via four entries in the signal_timing_plan table.  The timings of the individual phases would be in the signal_timing_phase table (one entry for each phase / timing_plan combination).

**Comment by mike-mahut** [comment]
in addition to the actual timing, the "signal phase concurrency" (i.e. ring-barrier-position structure) must also be able to change at different times of the day -- I don't believe that this is supported in the current design. Its quite critical.

**Comment by ianberg-volpe** [comment]
resolved by #40
