### ISSUE TITLE
Associating shape information with road_links

### ISSUE THREAD

**Issue by ssmith55** [zephyr-data-specs/GMNS#3]
GMNS currently uses two data elements to represent a undivided road:
-  a pair of road_links, one for each direction, which contain information needed for routing (e.g,, from_node_id, to_node_id, capacity)
-  a physical link, which has the length and shape points for the road.  
It may easier for some software packages to have both the shapepoints and the routing information in the same object.   Can we do this efficiently without duplicating shapepoints?

**Comment by ssmith55** [comment]
We've tested generation of WKT shapepoints from samples of two real-world networks.  Shapepoints were consuming an average of 150 Bytes / link on the higher-fidelity network.  The disk space/memory penalty for duplicating shapepoints seems to be manageable.    We've also created a branch of GMNS that moves the information from link_geometry to road_link and offroad_link, to further explore the implications of including the shape information in road_link and offroad_link.

**Comment by joshchea** [comment]
FYI: I tested the option of storing link polylines in a separate table - with from, to node reference and x, y, z for a true-shape all street network for the DVRPC (Philly) model [210,502 nodes, 582,868 links]. 

This format produced a text file ~65MB. I've uploaded the network here: [polyline data](https://ptv2box.ptvgroup.com/index.php/s/XnL7tGNHdRB76nS)

![dvrpc](https://user-images.githubusercontent.com/6776465/81819116-c150b380-94e3-11ea-8860-bcdd857ea75d.jpg)
