### ISSUE TITLE
Consistency in variables between link and link_tod (i.e. `toll`)

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#33]
It seems like there should be some consistency between the various intersecting files and therefore if it is defined in a "sub file" (i.e. lane or tod) then it should be defined in the base.

Therefore, `toll` should probably be in the `link` file

**Comment by ssmith55** [comment]
@anaaka and @ianberg-volpe ,  we are making changes to the TOD, link and segment files to improve the consistency of variables between parent and child files.  Will be implemented first in the updates branch
