### ISSUE TITLE
standardize uppercase vs lowercase for enums

### ISSUE THREAD

**Issue by ianberg-volpe** [zephyr-data-specs/GMNS#35]
When trying out @e-lo's GMNSpy (#34), I noticed that we have some enums that are in uppercase (allowed uses: SHOULDER, PARKING, WALK, ALL, BIKE, AUTO, HOV2, HOV3, TRUCK, BUS), and lowercase (parking: unknown, none, parallel, angle, other).

**Comment by e-lo** [comment]
Agree. I would suggest EVERYTHING be LoWerCaSe: variables, enums, etc r
