### ISSUE TITLE
signal_timing_plan attributes

### ISSUE THREAD

**Issue by mike-mahut** [zephyr-data-specs/GMNS#42]
One additional attribute that would help complete the currently supported functionality/options is an indicator of whether the offset is measured to the start or the end of the "coord_phase"; both (start and end) are used in different situations

**Comment by ssmith55** [comment]
coord_ref_to field has been added.  Possible values:  begin_of_green, begin_of_yellow, begin_of_red

**Comment by mike-mahut** [comment]
In practice I have only seen the start-of-green and end-of-green as options: I believe they would suffice, but the proposed 3 options would be fine too.

**Comment by ianberg-volpe** [comment]
resolved in #40
