### ISSUE TITLE
Add geometry to movement table

### ISSUE THREAD

**Issue by ssmith55** [zephyr-data-specs/GMNS#49]
Will enable display of movements in a zoomed-in GIS map

**Comment by ssmith55** [comment]
Added the field to the end of the movement table.  Question:  should we also add geometry_id (to enable geometries to be stored in a separate place?  This would require re-visiting the key of the geometry table).

**Comment by ianberg-volpe** [comment]
one option: make the key to the geometry table arbitrary, and add optional columns for references to places from which the geometries might come (e.g., `sharedstreets_id`, `osm_way_id`, etc.)
