### ISSUE TITLE
Complete examples

### ISSUE THREAD

**Issue by pedrocamargo** [zephyr-data-specs/GMNS#56]
It would be helpful to have examples where all tables exist to allow for testing of software written against the specification.

To be more specific, I am working on the GMN importer/exporter for both AequilibraE and Polaris, and there are no examples that include the zone table.

**Comment by ssmith55** [comment]
Good point!  I'll develop an example zone table during the next day or two, and will post it in the development branch.  Thank you for your work in the importer/exporters.

**Comment by ssmith55** [comment]
The Arlington_Signals and Cambridge examples now have zone tables.  They are based on Census block groups with geometries taken from TIGER.  Please look at the examples in the development branc
[ArlCtrZoneGMNS.csv](https://github.com/zephyr-data-specs/GMNS/files/9290290/ArlCtrZoneGMNS.csv)
[CambZoneGMNS.csv](https://github.com/zephyr-data-specs/GMNS/files/9290293/CambZoneGMNS.csv)
h

**Comment by pedrocamargo** [comment]
Thanks, @ssmith55 !
