### ISSUE TITLE
Move schema to 'code'

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#6]
Right now the schema itself is only defined in the wiki. I am suggesting that we define it in 'code' for the following reasons:
1. It is what most other data standards are doing,
2. It make evaluating changes and observing change history and versioning very obvious and straightforward
3. it makes approvals and reviews using pull-requests a lot easier

**Comment by ssmith55** [comment]
What we can do soon:  put the markdown files in the code
Longer term (something for our summer intern), it may make sense to implement Python classes, with both the definitions and basic constructor and test code.

**Comment by e-lo** [comment]
Rather than writing your own python classes, suggest using some sort of existing standard for specifying the schema such as https://specs.frictionlessdata.io/table-schema/

It is by no means perfect, but easy to validate in various languages (i.e. https://github.com/frictionlessdata/tableschema-py)

Then you can use tools like https://github.com/AntoineAugusti/table-schema-to-markdown to generate the markdown for the documentation itself.

**Comment by ianberg-volpe** [comment]
Re: the "what we can do soon" part of @ssmith55's comment above, the [spec-as-code branch](https://github.com/zephyr-data-specs/GMNS/tree/spec-as-code) now has Markdown files of each table's wiki page exported to the "code" part of the repository.

**Comment by ianberg-volpe** [comment]
This was resolved by the creation of the [json files](https://github.com/zephyr-data-specs/GMNS/tree/master/Specification/) in v0.91 (#45)
