### ISSUE TITLE
Rename branches to updated general defaults used.

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#62]
As a contributor, I'd like to expect consistent naming in my branches across repositories.  Current general defaults across github are:

- `main` (previously `master`)
- `develop`

See: https://github.com/github/renaming

**Comment by pedrocamargo** [comment]
Excellent suggestion

**Comment by ssmith55** [comment]
Renamed the development branch to develop.  Git code for your local environments:
  
git branch -m development develop
  git fetch origin
  git branch -u origin/develop develop
  git remote set-head origin -a
