### ISSUE TITLE
Efficient directory names

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#63]
As a programatic user, I'd like to more efficiently navigate the GMNS spec directory and not worry about fussy capitalization.

If approved by community, I (@e-lo) am happy to implement.

### Proposed solution

Adopt following folder structure:

```
spec\
examples\ #small network examples dir...without stray .csvs in base dir
usage\ #example validation and usage notebooks, currently in validation tools and conversion tools dir
docs\ 
  spec\ # all markdown versions of spec
  img\  # all image files
```

**Comment by e-lo** [comment]
cc: @joecastiglione on if community would like me to implement.

**Comment by ssmith55** [comment]
Thank you for the suggestion.  Other users, notably AequilibraE, are using the current directory structure in some examples.   I am fine with this change, but would like to save it for the next release, with advance notification to the user community.

**Comment by pedrocamargo** [comment]
Excellent suggestion

**Comment by ssmith55** [comment]
Let's do it, starting with the development (soon to be develop) branch.
