### ISSUE TITLE
Auto-generate md documentation

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#64]
As a maintainer, I don't want to have to worry about updating the markdown documentation to be in sync with the code-based specification.

As a user, I want the certainty that the markdown documentation is the same as the code-based specification.

## Proposed Solution

The markdown documentation can and should be automatically generated from the code-based documentation. This has been proven in the `gmnspy` package and I (@e-lo) am happy to implement here if given go-ahead by community.

**Comment by e-lo** [comment]
cc: @joecastiglione on if community would like me to implement.

**Comment by ianberg-volpe** [comment]
should've been closed by #88
