### ISSUE TITLE
Add codeowners files or otherwise automatically assign reviews for pull requests

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#69]
As a contributor, I'd like to make sure my pull requests are considered in a timely manner.

## Proposed Solution

Add [CODEOWNERs file ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)or [otherwise automatically assign pull requests to reviewers](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team).

Must be completed by someone with owner/manager rights to the repo.

**Comment by ianberg-volpe** [comment]
Added in a1ff064 (and assigned @ssmith55 and I to that role)
