### ISSUE TITLE
Road associations. Combine offroad and road links

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#7]
I've been writing some code to be able to validate and process GMNS data as well as writing the spec as a json csv spec per the @frictionlessdata [table-schema](https://specs.frictionlessdata.io/table-schema/). In working with the spec a little the biggest issue I see at the moment is the unnecessary duplication of "link" infrastructure between the offroad and road links and the inability to connect it in a one-to-one fashion. 

Below is an (incomplete) example of a small grid with offstreet links (red dotted) for walkways and road links (blue). While this may seem duplicative when you can associate a 'sidewalk' with a road link, this is, in fact, the way much of the open street map network is coded in downtown areas...and this is what the network will look like in packages like OSMNX when imported (at least for A and B).  There are separate links in the network graph created for each place that the road link intersects the offroad link.

**Relationship between links**
There is potentially a complex relationship between the [offroad links](https://github.com/zephyr-data-specs/GMNS/wiki/Offroad_Link) and the onroad links (`assoc_road_link_id`) as well as offroad links and nodes (`assoc_node_id`), but I would assume that link 3-->5 would be associated with A-->C and 6-->7 would be associated with A-->B?
 
![image](https://user-images.githubusercontent.com/794787/79916570-d69f5a00-83dd-11ea-8837-eaf060d80138.png)

I would propose that this relationship need not be exclusive to offroad links and that in fact there may be road links you may want to associate together as well as road nodes that you may want to associate together.  I propose the following:
1. offroad and road links and nodes combined into a single table
2. nodes can have 'parent' nodes (this is how GTFS deals with "stops" being part of "stations" and would work for crosswalks too. 
3. links can have 'parent' links (will work well for HOV lanes that are separate links)

**Comment by ianberg-volpe** [comment]
The [spec-as-code branch](https://github.com/zephyr-data-specs/GMNS/tree/spec-as-code) proposes some updates related to this issue (see commit 3d56e8722d45b55b65668dbd52d4662219a2010e):
- added `parent_node_id` field to the node table
- `road_link` table is renamed `link`; `road_link_id` field becomes `link_id`
- `offroad_link` table is removed
    - the `dir_flag` field can now have value 0 (undirected) in addition to 1 (travel with shapepoint direction) and -1 (travel against shapepoints)
- added `parent_link_id` field to the link table

**Comment by ssmith55** [comment]
dir_flag is serving two purposes:  indicating direction of shapepoints, wrt from_node and to_node, and indicating whether the link is directed.  Perhaps 2 fields would be cleaner:
directed = 1 if link is directed, 0 if undirected
dir_flag =  indicates whether shapepoints go in the from_node - to_node direction

**Comment by joshchea** [comment]
Integration of the network could potentially be achieved by specification of use i.e. tsys or mode string (delimited space or semicolon) on links and/or movement. When a search graph is generated for routing - the mode string is used accordingly. 

![integrated_multimodal](https://user-images.githubusercontent.com/6776465/81824113-f52ed780-94e9-11ea-8772-2183446e80f6.jpg)

**Comment by e-lo** [comment]
@joshchea I think the pull request essentially implements that suggestion
