### ISSUE TITLE
Location LR: dependent upon link geometry?

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#8]
The `lr` field in the [`location`](https://github.com/zephyr-data-specs/GMNS/wiki/Location) table is ambiguous about if it is using link geometry or not.  

Suggest:  _if link_geometry exists, it is used. Otherwise, link geometry is assumed to be a crow-fly distance from A node to B node._

Note: this issue also exists in the [segment table](https://github.com/zephyr-data-specs/GMNS/wiki/Segment).

**Comment by ssmith55** [comment]
Agree with the suggestion; documentation to be updated
