### ISSUE TITLE
x_coord, y_coord in locations provides duplicative (potentially conflicting) information

### ISSUE THREAD

**Issue by e-lo** [zephyr-data-specs/GMNS#9]
Per the current [`location`](https://github.com/zephyr-data-specs/GMNS/wiki/Location) table, `x_coord` and `y_coord` can be derived from the Link, Ref_Node and LR.

This sets up the potential for having duplicative/conflicting information.  
- If x_coord and y_coord are provided...should they be checked against this?  
- If conflicting, which should govern?

Suggest deleting `x_coord` and `y_coord` or including them as placeholders for calculated values.

**Comment by ssmith55** [comment]
We can imagine a dataset granular enough where the location might have coordinates that are offset from the link, e.g., a bus stop (and you would want to display that in a GIS).   LR-derived coordinates would lie on the link. So, Ian and I would actually recommend the opposite priority:
-	If XY data are present, those take priority over any calculated version using the LR.
-	If XY data are blank, that could signal to a calculation tool that they could be filled in with calculated info.

**Comment by e-lo** [comment]
In that case, I would suggest having either but not both...
